services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: coolschool
      MYSQL_USER: cooluser
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
volumes:
  mysql-data: